use core::str;
use std::{fmt, io, str::FromStr};

use hex::FromHexError;
use hmac::{
    Hmac, Mac,
    digest::{OutputSizeUser, typenum::Unsigned},
};
use rand::{CryptoRng, Rng, rngs::OsRng};
use sha2::Sha256;
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt},
    net::TcpStream,
};

// # Authentication protocol
//
// `psk`              : pre-shared key
// `challenge`        : 256 bytes long randomly generated byte string
// `client_challenge` : challenge generated by the client
// `server_challenge` : challenge generated by the server
// `server_proof`     : HMAC-SHA-256(psk, client_challenge)
// `client_proof`     : HMAC_SHA-256(psk, server_challenge)
//
// 1. Client sends `client_challenge` to the server
// 2. Server sends `server_proof` and `server_challenge` to the client
// 3. Client verifies `server_proof`. If it's valid, it send `client_proof` to the server. Otherwise
// it closes the connection and returns "permission denied" error.
// 4. Server verifies `client_proof`. If it's valid, the client is authenticated. Otherwise it
// closes the connection.
//
const AUTH_CHALLENGE_SIZE: usize = 256;
const AUTH_PROOF_SIZE: usize = <<Sha256 as OutputSizeUser>::OutputSize as Unsigned>::USIZE; // 32

#[derive(Clone, Copy, Eq, PartialEq)]
pub struct AuthKey([u8; Self::SIZE]);

impl AuthKey {
    pub const SIZE: usize = 32;

    pub fn generate<R: Rng + CryptoRng + ?Sized>(rng: &mut R) -> Self {
        Self(rng.r#gen())
    }

    pub fn random() -> Self {
        Self::generate(&mut OsRng)
    }

    pub fn as_bytes(&self) -> &[u8] {
        self.0.as_slice()
    }
}

impl fmt::Debug for AuthKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("AuthKey").finish_non_exhaustive()
    }
}

impl fmt::LowerHex for AuthKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for b in self.0 {
            write!(f, "{:02x}", b)?;
        }

        Ok(())
    }
}

impl FromStr for AuthKey {
    type Err = AuthKeyParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut bytes = [0; Self::SIZE];
        hex::decode_to_slice(s, &mut bytes)?;

        Ok(Self(bytes))
    }
}

#[derive(Debug)]
pub struct AuthKeyParseError(pub hex::FromHexError);

impl From<FromHexError> for AuthKeyParseError {
    fn from(e: FromHexError) -> Self {
        Self(e)
    }
}

/// Server-side part of the authentication protocol.
pub(super) async fn server(socket: &mut TcpStream, auth_key: &AuthKey) -> io::Result<()> {
    let mut client_challenge = [0; AUTH_CHALLENGE_SIZE];
    socket.read_exact(&mut client_challenge).await?;

    let server_proof = hmac(auth_key, &client_challenge).finalize();

    let mut server_challenge = [0; AUTH_CHALLENGE_SIZE];
    OsRng.fill(&mut server_challenge);

    socket.write_all(&server_proof.into_bytes()).await?;
    socket.write_all(&server_challenge).await?;

    let mut client_proof = [0; AUTH_PROOF_SIZE];
    socket.read_exact(&mut client_proof).await?;

    hmac(auth_key, &server_challenge)
        .verify_slice(&client_proof)
        .map_err(|_| io::Error::other("authentication challenge failed"))?;

    Ok(())
}

/// Client-side part of the authentication protocol.
pub(super) async fn client(socket: &mut TcpStream, auth_key: &AuthKey) -> io::Result<()> {
    let mut client_challenge = [0; AUTH_CHALLENGE_SIZE];
    OsRng.fill(&mut client_challenge);
    socket.write_all(&client_challenge).await?;

    let mut server_proof = [0; AUTH_PROOF_SIZE];
    socket.read_exact(&mut server_proof).await?;

    hmac(auth_key, &client_challenge)
        .verify_slice(&server_proof)
        .map_err(|error| io::Error::new(io::ErrorKind::PermissionDenied, error))?;

    let mut server_challenge = [0; AUTH_CHALLENGE_SIZE];
    socket.read_exact(&mut server_challenge).await?;

    let client_proof = hmac(auth_key, &server_challenge).finalize();
    socket.write_all(&client_proof.into_bytes()).await?;

    Ok(())
}

fn hmac(key: &AuthKey, message: &[u8]) -> Hmac<Sha256> {
    Hmac::<Sha256>::new_from_slice(key.as_bytes())
        .expect("invalid HMAC key size")
        .chain_update(message)
}
